receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"
processors:
  batch:

exporters:
  opensearch/trace:
    http:
      endpoint: http://opensearch:9200
      tls:
        insecure: true
  opensearch/log:
    http:
      endpoint: http://opensearch:9200
      tls:
        insecure: true
  otlp/data-prepper:
    endpoint: data-prepper:21891
    tls:
      insecure: true

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [opensearch/log]
    traces:
      receivers: [otlp]
      exporters: [opensearch/trace, otlp/data-prepper]
      processors: [batch]
