receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:

exporters:
  elasticsearch:
    endpoints: ["http://localhost:9200"]
    index: "otel-%{+yyyy.MM.dd}"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch]
