receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
  batch:

exporters:
  opensearch/trace:
    http:
      endpoint: http://opensearch:9200
      tls:
        insecure: true
  opensearch/log:
    http:
      endpoint: http://opensearch:9200
      tls:
        insecure: true

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [opensearch/log]
    traces:
      receivers: [otlp]
      exporters: [opensearch/trace]
      processors: [batch]
